/**
 * Comprehensive QA test: 30 variants of the invitation letter.
 * Run: node test-pdf-qa.mjs
 */
import { writeFileSync, mkdirSync } from 'fs';
import generatePDF from './api/lib/generate-pdf.js';

const OUT_DIR = './temporary pdf/qa';
mkdirSync(OUT_DIR, { recursive: true });

// ─── Helper: base host data ───
const hostBase = {
  'a-nombre': 'Juan Carlos López Mendoza',
  'a-genero': 'masculino',
  'a-nacionalidad': 'Mexicana',
  'a-nacimiento': '1985-08-22',
  'a-id-tipo': 'ine',
  'a-id-num': 'LOPM850822HDFRND09',
  'a-calle': 'Calle Reforma 456',
  'a-colonia': 'Juárez',
  'a-delegacion': 'Cuauhtémoc',
  'a-ciudad': 'Ciudad de México',
  'a-estado': 'Ciudad de México',
  'a-cp': '06600',
  'a-telefono': '55 1234 5678',
  'a-email': 'juan@ejemplo.com',
  'a-ocupacion': 'Ingeniero en Sistemas',
  'a-empresa': 'Grupo Bimbo',
};

// ─── Helper: base visitor data ───
const visitorBase = {
  'v-nombre': 'María Alejandra Rodríguez Pérez',
  'v-genero': 'femenino',
  'v-nacimiento': '1990-04-15',
  'v-nacionalidad': 'Venezolana',
  'v-pasaporte': 'AB1234567',
  'v-residencia': 'Venezuela',
  'v-calle': 'Av. Bolívar 123, Apto 4B',
  'v-ciudad': 'Caracas',
  'v-provincia': 'Distrito Capital',
  'v-cp': '1010',
  'v-ocupacion': 'Ingeniera de Software',
  'v-email': 'maria@example.com',
};

const flightEntry = {
  'ingreso_tipo': 'aereo',
  'ing-aeropuerto': 'Aeropuerto Internacional de la Ciudad de México (AICM)',
  'ing-aerolinea': 'Avianca',
  'ing-vuelo': 'AV204',
  'ing-fecha': '2026-04-10',
};

const flightExit = {
  'salida_tipo': 'aereo',
  'sal-aeropuerto': 'Aeropuerto Internacional de la Ciudad de México (AICM)',
  'sal-aerolinea': 'Avianca',
  'sal-vuelo': 'AV205',
  'sal-fecha': '2026-04-24',
};

const landExit = {
  'salida_tipo': 'terrestre',
  'sal-cruce': 'Nuevo Laredo',
  'sal-fecha': '2026-04-24',
};

const seaEntry = {
  'ingreso_tipo': 'maritimo',
  'ing-puerto': 'Puerto de Cozumel',
  'ing-fecha': '2026-05-01',
};

const seaExit = {
  'salida_tipo': 'maritimo',
  'sal-puerto': 'Puerto de Cozumel',
  'sal-fecha': '2026-05-08',
};

const landEntry = {
  'ingreso_tipo': 'terrestre',
  'ing-cruce': 'Tijuana',
  'ing-fecha': '2026-06-01',
};

// ─── Helper: delete single-accommodation fields for completo ───
function cleanForCompleto(data) {
  const d = { ...data };
  delete d['j-actividades'];
  delete d['j-aloj-nombre'];
  delete d['j-al-calle'];
  delete d['j-al-colonia'];
  delete d['j-al-delegacion'];
  delete d['j-al-ciudad'];
  delete d['j-al-estado'];
  delete d['j-al-cp'];
  delete d['aloj_es_anfitrion'];
  return d;
}

// ════════════════════════════════════════════════════════════════════
// PLAN ESENCIAL — 15 variants
// ════════════════════════════════════════════════════════════════════

const esenciales = [
  {
    name: 'E01-fem-turismo-hotel-gastos-aereo',
    desc: 'Femenino, turismo, hotel, anfitrión paga gastos, aéreo/aéreo',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'j-motivo': 'turismo',
      'j-actividades': 'Turismo cultural, visita a museos, recorrido gastronómico por la ciudad, y visita a Teotihuacán.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Histórico Central',
      'j-al-calle': 'Calle 5 de Mayo 12',
      'j-al-colonia': 'Centro Histórico',
      'j-al-delegacion': 'Cuauhtémoc',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '06000',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos', 'transporte'],
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Somos amigos desde la universidad.',
      'a-tiempo-anios': '8',
      'a-tiempo-meses': '0',
    },
  },
  {
    name: 'E02-masc-negocios-anfitrion-sinGastos-terrestre',
    desc: 'Masculino, negocios, domicilio anfitrión, sin gastos, terrestre, familiar hermano',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...landExit,
      'v-nombre': 'Carlos Eduardo Gómez Martín',
      'v-genero': 'masculino',
      'v-ocupacion': 'Contador Público',
      'v-nacimiento': '1988-11-03',
      'v-pasaporte': 'CD7654321',
      'j-motivo': 'negocios',
      'j-actividades': 'Reuniones de trabajo y visita a proveedores.',
      'aloj_es_anfitrion': 'si',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico'],
      'a-vinculo': 'familiar',
      'a-parentesco': 'hermano',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
      'a-empresa': '',
    },
  },
  {
    name: 'E03-fem-estudios-hotel-sinNombre-gastosTodos',
    desc: 'Femenino, estudios, hotel sin nombre, anfitrión paga todos los gastos',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Lucía Fernanda Herrera Castro',
      'v-genero': 'femenino',
      'v-nacionalidad': 'Colombiana',
      'v-residencia': 'Colombia',
      'v-calle': 'Carrera 7 #45-12',
      'v-ciudad': 'Bogotá',
      'v-provincia': 'Cundinamarca',
      'v-cp': '110311',
      'v-ocupacion': 'Estudiante de Medicina',
      'j-motivo': 'estudios',
      'j-actividades': 'Programa de intercambio académico en la UNAM, asistencia a conferencias médicas.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': '',
      'j-al-calle': 'Av. Universidad 3000',
      'j-al-colonia': 'Ciudad Universitaria',
      'j-al-delegacion': 'Coyoacán',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '04510',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte', 'actividades'],
      'transporte_mx': ['anfitrion'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en un congreso médico en Colombia hace varios años.',
      'a-tiempo-anios': '3',
      'a-tiempo-meses': '6',
    },
  },
  {
    name: 'E04-masc-turismo-anfitrion-padre',
    desc: 'Masculino, turismo, domicilio anfitrión, familiar padre (consanguíneo)',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Roberto Alejandro López García',
      'v-genero': 'masculino',
      'v-nacimiento': '1958-02-14',
      'v-nacionalidad': 'Española',
      'v-residencia': 'España',
      'v-calle': 'Calle Gran Vía 45, 3ºB',
      'v-ciudad': 'Madrid',
      'v-provincia': 'Madrid',
      'v-cp': '28013',
      'v-pasaporte': 'ESP9876543',
      'v-ocupacion': 'Jubilado',
      'j-motivo': 'turismo',
      'j-actividades': 'Visitar a la familia, recorrido por la Ciudad de México, y descanso.',
      'aloj_es_anfitrion': 'si',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte'],
      'transporte_mx': ['anfitrion', 'transporte_publico'],
      'a-vinculo': 'familiar',
      'a-parentesco': 'padre',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
    },
  },
  {
    name: 'E05-fem-medico-hotel-pareja-novia',
    desc: 'Femenino, tratamiento médico, hotel, pareja novia',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Ana Patricia Ruiz Delgado',
      'v-genero': 'femenino',
      'v-nacimiento': '1995-07-22',
      'v-nacionalidad': 'Peruana',
      'v-residencia': 'Perú',
      'v-calle': 'Av. Javier Prado 1234',
      'v-ciudad': 'Lima',
      'v-provincia': 'Lima',
      'v-cp': '15036',
      'v-pasaporte': 'PE5551234',
      'v-ocupacion': 'Diseñadora Gráfica',
      'j-motivo': 'tratamientos_medicos',
      'j-actividades': 'Consultas médicas en Hospital ABC, estudios clínicos y seguimiento postoperatorio.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Camino Real',
      'j-al-calle': 'Mariano Escobedo 700',
      'j-al-colonia': 'Anzures',
      'j-al-delegacion': 'Miguel Hidalgo',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '11590',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'medicos'],
      'transporte_mx': ['transporte_publico'],
      'a-vinculo': 'pareja',
      'a-parentesco': 'novio',
      'a-vinculo-detalle': 'Somos novios desde 2022.',
      'a-tiempo-anios': '4',
      'a-tiempo-meses': '0',
    },
  },
  {
    name: 'E06-masc-transito-hotel-amistad-largo',
    desc: 'Masculino, tránsito, hotel, amistad, detalle largo',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Jean Pierre Dubois',
      'v-genero': 'masculino',
      'v-nacimiento': '1982-12-01',
      'v-nacionalidad': 'Francesa',
      'v-residencia': 'Francia',
      'v-calle': '15 Rue de Rivoli',
      'v-ciudad': 'París',
      'v-provincia': 'Île-de-France',
      'v-cp': '75001',
      'v-pasaporte': 'FR12345678',
      'v-ocupacion': 'Fotógrafo profesional',
      'j-motivo': 'transito',
      'j-actividades': 'Escala de 5 días antes de continuar viaje a Guatemala, recorrido turístico por el centro histórico.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Zócalo Central',
      'j-al-calle': 'Av. 5 de Mayo 61',
      'j-al-colonia': 'Centro Histórico',
      'j-al-delegacion': 'Cuauhtémoc',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '06000',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['auto_rentado'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos durante un proyecto fotográfico en París en 2018 y hemos colaborado profesionalmente desde entonces.',
      'a-tiempo-anios': '7',
      'a-tiempo-meses': '6',
    },
  },
  {
    name: 'E07-fem-turismo-anfitrion-hija',
    desc: 'Femenino, turismo, domicilio anfitrión, familiar hija (consanguíneo)',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Sofía López Ramírez',
      'v-genero': 'femenino',
      'v-nacimiento': '2005-09-30',
      'v-nacionalidad': 'Estadounidense',
      'v-residencia': 'Estados Unidos',
      'v-calle': '123 Main St, Apt 5',
      'v-ciudad': 'Houston',
      'v-provincia': 'Texas',
      'v-cp': '77001',
      'v-pasaporte': 'US987654321',
      'v-ocupacion': 'Estudiante de preparatoria',
      'j-motivo': 'turismo',
      'j-actividades': 'Vacaciones familiares, visita a Chapultepec, Xochimilco y Six Flags.',
      'aloj_es_anfitrion': 'si',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte', 'actividades'],
      'transporte_mx': ['anfitrion'],
      'a-vinculo': 'familiar',
      'a-parentesco': 'hijo',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
    },
  },
  {
    name: 'E08-masc-negocios-hotel-pareja-conyuge',
    desc: 'Masculino, negocios, hotel, pareja cónyuge',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'a-genero': 'femenino',
      'a-nombre': 'Laura Patricia Sánchez Moreno',
      'a-id-num': 'SAML900101MDFSRN05',
      'a-ocupacion': 'Abogada',
      'a-empresa': 'Despacho Sánchez & Asociados',
      'v-nombre': 'David Alejandro Torres Ríos',
      'v-genero': 'masculino',
      'v-nacimiento': '1987-03-18',
      'v-nacionalidad': 'Argentino',
      'v-residencia': 'Argentina',
      'v-calle': 'Av. Corrientes 1234',
      'v-ciudad': 'Buenos Aires',
      'v-provincia': 'Buenos Aires',
      'v-cp': 'C1043',
      'v-pasaporte': 'AR44556677',
      'v-ocupacion': 'Director de Marketing',
      'j-motivo': 'negocios',
      'j-actividades': 'Reuniones corporativas, firma de contrato comercial y visita a sucursales.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel W Mexico City',
      'j-al-calle': 'Campos Elíseos 252',
      'j-al-colonia': 'Polanco',
      'j-al-delegacion': 'Miguel Hidalgo',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '11560',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico', 'auto_rentado'],
      'a-vinculo': 'pareja',
      'a-parentesco': 'conyuge',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '5',
      'a-tiempo-meses': '3',
    },
  },
  {
    name: 'E09-masc-turismo-hotel-maritimo',
    desc: 'Masculino, turismo, hotel, entrada/salida marítima',
    data: {
      ...hostBase, ...visitorBase, ...seaEntry, ...seaExit,
      'a-ciudad': 'Cancún',
      'a-estado': 'Quintana Roo',
      'a-calle': 'Blvd. Kukulcán Km 12',
      'a-colonia': 'Zona Hotelera',
      'a-delegacion': 'Benito Juárez',
      'a-cp': '77500',
      'v-nombre': 'James Robert Williams',
      'v-genero': 'masculino',
      'v-nacimiento': '1975-06-15',
      'v-nacionalidad': 'Estadounidense',
      'v-residencia': 'Estados Unidos',
      'v-calle': '456 Ocean Drive',
      'v-ciudad': 'Miami',
      'v-provincia': 'Florida',
      'v-cp': '33139',
      'v-pasaporte': 'US123789456',
      'v-ocupacion': 'Arquitecto',
      'j-motivo': 'turismo',
      'j-actividades': 'Buceo en arrecifes, visita a ruinas mayas, recorrido por la isla de Cozumel.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Grand Fiesta Americana',
      'j-al-calle': 'Blvd. Kukulcán Km 9.5',
      'j-al-colonia': 'Zona Hotelera',
      'j-al-delegacion': 'Benito Juárez',
      'j-al-ciudad': 'Cancún',
      'j-al-estado': 'Quintana Roo',
      'j-al-cp': '77500',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['auto_rentado'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en una conferencia de arquitectura en 2019.',
      'a-tiempo-anios': '6',
      'a-tiempo-meses': '0',
    },
  },
  {
    name: 'E10-fem-turismo-hotel-terrestre-entrada',
    desc: 'Femenino, turismo, hotel, entrada terrestre y salida aérea',
    data: {
      ...hostBase, ...visitorBase, ...landEntry, ...flightExit,
      'sal-fecha': '2026-06-15',
      'v-nombre': 'Valentina González Muñoz',
      'v-genero': 'femenino',
      'v-nacimiento': '1993-01-05',
      'v-nacionalidad': 'Chilena',
      'v-residencia': 'Chile',
      'v-calle': 'Av. Providencia 2309',
      'v-ciudad': 'Santiago',
      'v-provincia': 'Región Metropolitana',
      'v-cp': '7500000',
      'v-pasaporte': 'CL11223344',
      'v-ocupacion': 'Periodista',
      'j-motivo': 'turismo',
      'j-actividades': 'Ruta de vinos por Valle de Guadalupe, visita a Ensenada y gastronomía local.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Boutique Valle',
      'j-al-calle': 'Carretera Tecate-Ensenada Km 73',
      'j-al-colonia': 'Valle de Guadalupe',
      'j-al-delegacion': 'Ensenada',
      'j-al-ciudad': 'Ensenada',
      'j-al-estado': 'Baja California',
      'j-al-cp': '22750',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos'],
      'transporte_mx': ['auto_rentado'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos viajando por Sudamérica.',
      'a-tiempo-anios': '2',
      'a-tiempo-meses': '4',
    },
  },
  {
    name: 'E11-masc-actividades-anfitrion-tio',
    desc: 'Masculino, actividades no remuneradas, domicilio anfitrión, familiar tío',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Andrés Felipe Morales Quintero',
      'v-genero': 'masculino',
      'v-nacimiento': '2000-08-12',
      'v-nacionalidad': 'Ecuatoriana',
      'v-residencia': 'Ecuador',
      'v-calle': 'Av. Amazonas N34-56',
      'v-ciudad': 'Quito',
      'v-provincia': 'Pichincha',
      'v-cp': '170150',
      'v-pasaporte': 'EC98765432',
      'v-ocupacion': 'Voluntario social',
      'j-motivo': 'actividades_no_remuneradas',
      'j-actividades': 'Voluntariado en albergue infantil, talleres comunitarios.',
      'aloj_es_anfitrion': 'si',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos'],
      'transporte_mx': ['transporte_publico'],
      'a-vinculo': 'familiar',
      'a-parentesco': 'sobrino',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
    },
  },
  {
    name: 'E12-fem-turismo-hotel-cunada',
    desc: 'Femenino, turismo, hotel, familiar cuñada (no consanguíneo)',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Isabella Torres Vega',
      'v-genero': 'femenino',
      'v-nacimiento': '1991-04-28',
      'v-nacionalidad': 'Costarricense',
      'v-residencia': 'Costa Rica',
      'v-calle': 'Barrio Escalante, Calle 33',
      'v-ciudad': 'San José',
      'v-provincia': 'San José',
      'v-cp': '10101',
      'v-pasaporte': 'CR55667788',
      'v-ocupacion': 'Veterinaria',
      'j-motivo': 'turismo',
      'j-actividades': 'Visita al Museo Frida Kahlo, Coyoacán, mercados artesanales.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Casa de los Azulejos',
      'j-al-calle': 'Av. Madero 4',
      'j-al-colonia': 'Centro Histórico',
      'j-al-delegacion': 'Cuauhtémoc',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '06000',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico', 'auto_rentado'],
      'a-vinculo': 'familiar',
      'a-parentesco': 'cunado',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '10',
      'a-tiempo-meses': '0',
    },
  },
  {
    name: 'E13-masc-negocios-hotel-pasaporteMX-residente',
    desc: 'Masculino, negocios, hotel, anfitrión con pasaporte mexicano, ID tipo residente',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'a-id-tipo': 'residente',
      'a-id-num': 'RESPM1234567890',
      'v-nombre': 'Takeshi Yamamoto',
      'v-genero': 'masculino',
      'v-nacimiento': '1980-03-10',
      'v-nacionalidad': 'Japonesa',
      'v-residencia': 'Japón',
      'v-calle': '1-2-3 Shibuya',
      'v-ciudad': 'Tokio',
      'v-provincia': 'Tokio',
      'v-cp': '150-0002',
      'v-pasaporte': 'JP12345678',
      'v-ocupacion': 'Ejecutivo de ventas',
      'j-motivo': 'negocios',
      'j-actividades': 'Negociaciones comerciales con proveedores mexicanos, visita a planta de manufactura.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Presidente InterContinental',
      'j-al-calle': 'Campos Elíseos 218',
      'j-al-colonia': 'Polanco',
      'j-al-delegacion': 'Miguel Hidalgo',
      'j-al-ciudad': 'Ciudad de México',
      'j-al-estado': 'Ciudad de México',
      'j-al-cp': '11560',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Relación profesional desde 2017.',
      'a-tiempo-anios': '9',
      'a-tiempo-meses': '0',
    },
  },
  {
    name: 'E14-fem-turismo-hotel-oaxaca-dedup',
    desc: 'Femenino, turismo, hotel en Oaxaca (delegación=ciudad dedup test)',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'a-ciudad': 'Oaxaca de Juárez',
      'a-estado': 'Oaxaca',
      'a-calle': 'Calle Macedonio Alcalá 200',
      'a-colonia': 'Centro',
      'a-delegacion': 'Oaxaca de Juárez',
      'a-cp': '68000',
      'v-nombre': 'Camila Restrepo Vélez',
      'v-genero': 'femenino',
      'v-nacimiento': '1994-11-20',
      'v-nacionalidad': 'Colombiana',
      'v-residencia': 'Colombia',
      'v-calle': 'Calle 10 #5-23',
      'v-ciudad': 'Medellín',
      'v-provincia': 'Antioquia',
      'v-cp': '050001',
      'v-pasaporte': 'CO99887766',
      'v-ocupacion': 'Chef',
      'j-motivo': 'turismo',
      'j-actividades': 'Recorrido gastronómico, mercado de Tlacolula, mezcalerías, Monte Albán.',
      'aloj_es_anfitrion': 'no',
      'j-aloj-nombre': 'Hotel Casa Oaxaca',
      'j-al-calle': 'García Vigil 407',
      'j-al-colonia': 'Centro',
      'j-al-delegacion': 'Oaxaca de Juárez',
      'j-al-ciudad': 'Oaxaca de Juárez',
      'j-al-estado': 'Oaxaca',
      'j-al-cp': '68000',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en un festival gastronómico.',
      'a-tiempo-anios': '1',
      'a-tiempo-meses': '8',
    },
  },
  {
    name: 'E15-masc-turismo-anfitrion-gastosOtro',
    desc: 'Masculino, turismo, anfitrión, gastos con "otro" concepto personalizado',
    data: {
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Miguel Ángel Fernández Soto',
      'v-genero': 'masculino',
      'v-nacimiento': '1970-05-08',
      'v-nacionalidad': 'Cubana',
      'v-residencia': 'Cuba',
      'v-calle': 'Calle Obispo 155',
      'v-ciudad': 'La Habana',
      'v-provincia': 'La Habana',
      'v-cp': '10100',
      'v-pasaporte': 'CU44332211',
      'v-ocupacion': 'Músico profesional',
      'j-motivo': 'turismo',
      'j-actividades': 'Visita cultural, conciertos, y recorrido por sitios históricos.',
      'aloj_es_anfitrion': 'si',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'otro'],
      'gastos-otro-texto': 'entradas a eventos culturales',
      'transporte_mx': ['anfitrion', 'transporte_publico'],
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Somos músicos y hemos colaborado en varios proyectos.',
      'a-tiempo-anios': '12',
      'a-tiempo-meses': '0',
    },
  },
];

// ════════════════════════════════════════════════════════════════════
// PLAN COMPLETO — 15 variants
// ════════════════════════════════════════════════════════════════════

const completos = [
  {
    name: 'C01-2dest-2comp-turismo-gastos',
    desc: '2 destinos, 2 acompañantes, turismo, anfitrión paga',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Somos amigos desde la universidad.',
      'a-tiempo-anios': '8',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos', 'transporte'],
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      companions: [
        { nombre: 'Pedro Luis Rodríguez Pérez', genero: 'masculino', nacimiento: '1988-11-03', nacionalidad: 'Venezolana', pasaporte: 'CD7654321', vinculo: 'familiar', parentesco: 'sobrino', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '30', tiempo_meses: '0', ocupacion: 'Contador Público', mismo_domicilio: 'si' },
        { nombre: 'Ana Sofía Rodríguez', genero: 'femenino', nacimiento: '2015-06-20', nacionalidad: 'Venezolana', pasaporte: 'EF1112233', vinculo: 'pareja', parentesco: 'conyuge', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '5', tiempo_meses: '3', ocupacion: 'Estudiante', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Visita al Zócalo, Museo Nacional de Antropología, Chapultepec.', aloj_nombre: 'Hotel Histórico Central', aloj_calle: 'Calle 5 de Mayo 12', aloj_colonia: 'Centro Histórico', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06000', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-17' },
        { ciudad: 'Oaxaca de Juárez, Oaxaca', actividades: 'Monte Albán, artesanías, mezcal, Hierve el Agua.', aloj_nombre: '', aloj_calle: 'Macedonio Alcalá 305', aloj_colonia: 'Centro', aloj_delegacion: 'Oaxaca de Juárez', aloj_ciudad: 'Oaxaca de Juárez', aloj_estado: 'Oaxaca', aloj_cp: '68000', fecha_desde: '2026-04-17', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C02-1dest-1comp-turismo',
    desc: '1 destino, 1 acompañante (test "Destino:" sin número)',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Amigos del trabajo.',
      'a-tiempo-anios': '5',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico'],
      companions: [
        { nombre: 'Luis Fernando Rodríguez', genero: 'masculino', nacimiento: '1992-01-15', nacionalidad: 'Venezolana', pasaporte: 'VZ9988776', vinculo: 'amistad', parentesco: '', parentesco_otro: '', vinculo_detalle: 'Compañero de oficina.', tiempo_anios: '3', tiempo_meses: '0', ocupacion: 'Ingeniero Civil', mismo_domicilio: 'no', residencia: 'Venezuela', calle: 'Av. Libertador 890, Piso 3', ciudad: 'Caracas', provincia: 'Distrito Capital', cp: '1050' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Visita a museos y recorrido gastronómico.', aloj_nombre: 'Hotel Hilton', aloj_calle: 'Av. Juárez 70', aloj_colonia: 'Centro Histórico', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06010', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C03-0comp-2dest-negocios',
    desc: '0 acompañantes, 2 destinos, negocios (Plan Completo sin companions)',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'j-motivo': 'negocios',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Relación profesional.',
      'a-tiempo-anios': '4',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['auto_rentado'],
      companions: [],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Reuniones de trabajo en oficinas corporativas.', aloj_nombre: 'Hotel W', aloj_calle: 'Campos Elíseos 252', aloj_colonia: 'Polanco', aloj_delegacion: 'Miguel Hidalgo', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '11560', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-17' },
        { ciudad: 'Guadalajara, Jalisco', actividades: 'Conferencia tecnológica y networking.', aloj_nombre: '', aloj_calle: 'Av. Vallarta 1500', aloj_colonia: 'Americana', aloj_delegacion: 'Guadalajara', aloj_ciudad: 'Guadalajara', aloj_estado: 'Jalisco', aloj_cp: '44160', fecha_desde: '2026-04-17', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C04-4dest-1comp-turismo',
    desc: '4 destinos, 1 acompañante, turismo (stress test layout)',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...{ ...flightExit, 'sal-fecha': '2026-04-26' },
      'j-motivo': 'turismo',
      'a-vinculo': 'familiar',
      'a-parentesco': 'hermano',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos', 'transporte'],
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      companions: [
        { nombre: 'Pedro Luis Rodríguez', genero: 'masculino', nacimiento: '1988-11-03', nacionalidad: 'Venezolana', pasaporte: 'CD7654321', vinculo: 'familiar', parentesco: 'sobrino', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '30', tiempo_meses: '0', ocupacion: 'Abogado', mismo_domicilio: 'no', residencia: 'Venezuela', calle: 'Calle El Rosal 45, Urb. Las Mercedes', ciudad: 'Caracas', provincia: 'Distrito Capital', cp: '1060' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Zócalo, Antropología, Chapultepec.', aloj_nombre: 'Hotel Histórico', aloj_calle: '5 de Mayo 12', aloj_colonia: 'Centro', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06000', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-15' },
        { ciudad: 'Oaxaca de Juárez, Oaxaca', actividades: 'Monte Albán, artesanías, mezcal.', aloj_nombre: '', aloj_calle: 'Macedonio Alcalá 305', aloj_colonia: 'Centro', aloj_delegacion: 'Oaxaca de Juárez', aloj_ciudad: 'Oaxaca de Juárez', aloj_estado: 'Oaxaca', aloj_cp: '68000', fecha_desde: '2026-04-15', fecha_hasta: '2026-04-18' },
        { ciudad: 'San Cristóbal de las Casas, Chiapas', actividades: 'Cañón del Sumidero, mercados indígenas.', aloj_nombre: 'Posada del Abuelito', aloj_calle: 'Real de Guadalupe 18', aloj_colonia: 'Centro', aloj_delegacion: 'San Cristóbal de las Casas', aloj_ciudad: 'San Cristóbal de las Casas', aloj_estado: 'Chiapas', aloj_cp: '29200', fecha_desde: '2026-04-18', fecha_hasta: '2026-04-21' },
        { ciudad: 'Cancún, Quintana Roo', actividades: 'Playa, snorkel, Chichén Itzá, Xcaret.', aloj_nombre: 'Hotel Zona Hotelera', aloj_calle: 'Blvd. Kukulcán Km 9.5', aloj_colonia: 'Zona Hotelera', aloj_delegacion: 'Benito Juárez', aloj_ciudad: 'Cancún', aloj_estado: 'Quintana Roo', aloj_cp: '77500', fecha_desde: '2026-04-21', fecha_hasta: '2026-04-26' },
      ],
    }),
  },
  {
    name: 'C05-3dest-3comp-mixGender',
    desc: '3 destinos, 3 acompañantes mixed gender, turismo',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...{ ...flightExit, 'sal-fecha': '2026-04-25' },
      'v-nombre': 'Gabriela Martínez López',
      'v-genero': 'femenino',
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Amigas de la infancia.',
      'a-tiempo-anios': '20',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos'],
      'transporte_mx': ['anfitrion', 'transporte_publico'],
      companions: [
        { nombre: 'Ricardo Martínez López', genero: 'masculino', nacimiento: '1987-02-14', nacionalidad: 'Venezolana', pasaporte: 'VZ1122334', vinculo: 'familiar', parentesco: 'hermano', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Médico', mismo_domicilio: 'si' },
        { nombre: 'Daniela Martínez', genero: 'femenino', nacimiento: '2010-09-05', nacionalidad: 'Venezolana', pasaporte: 'VZ5566778', vinculo: 'familiar', parentesco: 'hijo', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Estudiante', mismo_domicilio: 'si' },
        { nombre: 'Tomás Gutiérrez Soto', genero: 'masculino', nacimiento: '1985-12-30', nacionalidad: 'Venezolana', pasaporte: 'VZ9900112', vinculo: 'amistad', parentesco: '', parentesco_otro: '', vinculo_detalle: 'Amigo cercano de la familia.', tiempo_anios: '15', tiempo_meses: '0', ocupacion: 'Profesor Universitario', mismo_domicilio: 'no', residencia: 'Venezuela', calle: 'Av. Universidad, Torre B, Apto 7C', ciudad: 'Maracaibo', provincia: 'Zulia', cp: '4001' },
      ],
      destinos: [
        { ciudad: 'Mérida, Yucatán', actividades: 'Visita a Chichén Itzá, cenotes, gastronomía yucateca.', aloj_nombre: 'Hotel Casa del Balam', aloj_calle: 'Calle 60 #488', aloj_colonia: 'Centro', aloj_delegacion: 'Mérida', aloj_ciudad: 'Mérida', aloj_estado: 'Yucatán', aloj_cp: '97000', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-15' },
        { ciudad: 'Playa del Carmen, Quintana Roo', actividades: 'Playa, Quinta Avenida, parque Xel-Há.', aloj_nombre: '', aloj_calle: 'Av. 10 Sur', aloj_colonia: 'Centro', aloj_delegacion: 'Solidaridad', aloj_ciudad: 'Playa del Carmen', aloj_estado: 'Quintana Roo', aloj_cp: '77710', fecha_desde: '2026-04-15', fecha_hasta: '2026-04-20' },
        { ciudad: 'Tulum, Quintana Roo', actividades: 'Ruinas de Tulum, cenote Dos Ojos, reserva de Sian Ka\'an.', aloj_nombre: 'Cabañas Tulum Beach', aloj_calle: 'Carretera Tulum-Boca Paila Km 4', aloj_colonia: 'Zona Hotelera', aloj_delegacion: 'Tulum', aloj_ciudad: 'Tulum', aloj_estado: 'Quintana Roo', aloj_cp: '77780', fecha_desde: '2026-04-20', fecha_hasta: '2026-04-25' },
      ],
    }),
  },
  {
    name: 'C06-2dest-1comp-fem-familiar-madre',
    desc: '2 destinos, 1 acompañante femenino, familiar madre (consanguíneo)',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Carmen Elena López de Rodríguez',
      'v-genero': 'femenino',
      'v-nacimiento': '1960-12-25',
      'v-nacionalidad': 'Venezolana',
      'v-pasaporte': 'VZ00112233',
      'v-ocupacion': 'Ama de casa',
      'j-motivo': 'turismo',
      'a-vinculo': 'familiar',
      'a-parentesco': 'padre',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '',
      'a-tiempo-meses': '',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte', 'actividades'],
      'transporte_mx': ['anfitrion'],
      companions: [
        { nombre: 'José Antonio López García', genero: 'masculino', nacimiento: '1958-03-15', nacionalidad: 'Venezolana', pasaporte: 'VZ44556600', vinculo: 'familiar', parentesco: 'padre', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Jubilado', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Visita familiar, Chapultepec, Xochimilco.', aloj_nombre: '', aloj_calle: 'Calle Reforma 456', aloj_colonia: 'Juárez', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06600', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-18' },
        { ciudad: 'Puebla, Puebla', actividades: 'Centro histórico, gastronomía, Cholula.', aloj_nombre: 'Hotel Mesón Sacristía', aloj_calle: 'Calle 6 Sur 304', aloj_colonia: 'Centro', aloj_delegacion: 'Puebla', aloj_ciudad: 'Puebla', aloj_estado: 'Puebla', aloj_cp: '72000', fecha_desde: '2026-04-18', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C07-1dest-2comp-estudios',
    desc: '1 destino, 2 acompañantes, estudios',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Laura Beatriz Campos Herrera',
      'v-genero': 'femenino',
      'v-nacimiento': '1998-07-03',
      'v-nacionalidad': 'Boliviana',
      'v-residencia': 'Bolivia',
      'v-calle': 'Av. Arce 2345',
      'v-ciudad': 'La Paz',
      'v-provincia': 'La Paz',
      'v-cp': '0000',
      'v-pasaporte': 'BO12341234',
      'v-ocupacion': 'Estudiante de posgrado',
      'j-motivo': 'estudios',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en un programa de intercambio.',
      'a-tiempo-anios': '2',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['transporte_publico'],
      companions: [
        { nombre: 'Diego Ramiro Campos', genero: 'masculino', nacimiento: '1997-01-20', nacionalidad: 'Boliviana', pasaporte: 'BO56785678', vinculo: 'familiar', parentesco: 'hermano', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Ingeniero Industrial', mismo_domicilio: 'no', residencia: 'Bolivia', calle: 'Calle Murillo 456', ciudad: 'La Paz', provincia: 'La Paz', cp: '0100' },
        { nombre: 'Patricia Herrera de Campos', genero: 'femenino', nacimiento: '1970-11-11', nacionalidad: 'Boliviana', pasaporte: 'BO99009900', vinculo: 'familiar', parentesco: 'padre', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Enfermera', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Curso intensivo en UNAM, conferencias académicas.', aloj_nombre: 'Residencia Universitaria UNAM', aloj_calle: 'Circuito Interior s/n', aloj_colonia: 'Ciudad Universitaria', aloj_delegacion: 'Coyoacán', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '04510', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C08-2dest-0comp-medico',
    desc: '2 destinos, 0 acompañantes, tratamiento médico',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Fernando José Reyes Amador',
      'v-genero': 'masculino',
      'v-nacimiento': '1965-09-08',
      'v-nacionalidad': 'Salvadoreña',
      'v-residencia': 'El Salvador',
      'v-calle': 'Col. Escalón, Calle La Reforma',
      'v-ciudad': 'San Salvador',
      'v-provincia': 'San Salvador',
      'v-cp': '1101',
      'v-pasaporte': 'SV22334455',
      'v-ocupacion': 'Empresario',
      'j-motivo': 'tratamientos_medicos',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Socios comerciales desde hace muchos años.',
      'a-tiempo-anios': '15',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'medicos'],
      'transporte_mx': ['anfitrion', 'transporte_publico'],
      companions: [],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Consulta médica en Hospital ABC, estudios clínicos.', aloj_nombre: 'Hotel Camino Real', aloj_calle: 'Mariano Escobedo 700', aloj_colonia: 'Anzures', aloj_delegacion: 'Miguel Hidalgo', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '11590', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-18' },
        { ciudad: 'Monterrey, Nuevo León', actividades: 'Tratamiento especializado en Hospital San José TecSalud.', aloj_nombre: 'Hotel Holiday Inn', aloj_calle: 'Av. Constitución 300', aloj_colonia: 'Centro', aloj_delegacion: 'Monterrey', aloj_ciudad: 'Monterrey', aloj_estado: 'Nuevo León', aloj_cp: '64000', fecha_desde: '2026-04-18', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C09-3dest-1comp-masc-terrestre',
    desc: '3 destinos, 1 acompañante masculino, entrada terrestre',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...landEntry, ...{ ...flightExit, 'sal-fecha': '2026-06-20' },
      'v-nombre': 'Diego Armando Suárez Peña',
      'v-genero': 'masculino',
      'v-nacimiento': '1991-02-28',
      'v-nacionalidad': 'Guatemalteca',
      'v-residencia': 'Guatemala',
      'v-calle': '6a Av. 5-55 Zona 1',
      'v-ciudad': 'Ciudad de Guatemala',
      'v-provincia': 'Guatemala',
      'v-cp': '01001',
      'v-pasaporte': 'GT11223300',
      'v-ocupacion': 'Ingeniero Civil',
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Compañeros de universidad.',
      'a-tiempo-anios': '10',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      companions: [
        { nombre: 'Lucía Gabriela Suárez', genero: 'femenino', nacimiento: '1993-05-10', nacionalidad: 'Guatemalteca', pasaporte: 'GT99887711', vinculo: 'pareja', parentesco: 'concubino', parentesco_otro: '', vinculo_detalle: 'Pareja del invitado principal.', tiempo_anios: '6', tiempo_meses: '0', ocupacion: 'Diseñadora Gráfica', mismo_domicilio: 'no', residencia: 'Guatemala', calle: 'Av. Reforma 12-01, Zona 10', ciudad: 'Ciudad de Guatemala', provincia: 'Guatemala', cp: '01010' },
      ],
      destinos: [
        { ciudad: 'San Cristóbal de las Casas, Chiapas', actividades: 'Turismo cultural, mercados indígenas.', aloj_nombre: 'Hotel Bo', aloj_calle: 'Av. 14 de Septiembre 2', aloj_colonia: 'Centro', aloj_delegacion: 'San Cristóbal de las Casas', aloj_ciudad: 'San Cristóbal de las Casas', aloj_estado: 'Chiapas', aloj_cp: '29200', fecha_desde: '2026-06-01', fecha_hasta: '2026-06-07' },
        { ciudad: 'Palenque, Chiapas', actividades: 'Zona arqueológica de Palenque, cascadas de Agua Azul.', aloj_nombre: '', aloj_calle: 'Av. Juárez 10', aloj_colonia: 'Centro', aloj_delegacion: 'Palenque', aloj_ciudad: 'Palenque', aloj_estado: 'Chiapas', aloj_cp: '29960', fecha_desde: '2026-06-07', fecha_hasta: '2026-06-13' },
        { ciudad: 'Villahermosa, Tabasco', actividades: 'Parque Museo La Venta, río Grijalva.', aloj_nombre: 'Hotel Hyatt Regency', aloj_calle: 'Av. Ruiz Cortines s/n', aloj_colonia: 'Centro', aloj_delegacion: 'Centro', aloj_ciudad: 'Villahermosa', aloj_estado: 'Tabasco', aloj_cp: '86000', fecha_desde: '2026-06-13', fecha_hasta: '2026-06-20' },
      ],
    }),
  },
  {
    name: 'C10-2dest-1comp-fem-pareja-novio',
    desc: '2 destinos, 1 acompañante femenina, pareja novio, anfitriona femenina',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'a-genero': 'femenino',
      'a-nombre': 'Mariana Isabel Gutiérrez Vega',
      'a-id-num': 'GUVM880515MDFTGR07',
      'a-ocupacion': 'Médica General',
      'a-empresa': 'Hospital Ángeles',
      'v-nombre': 'Sebastián Alejandro Ortiz Blanco',
      'v-genero': 'masculino',
      'v-nacimiento': '1990-10-18',
      'v-nacionalidad': 'Uruguaya',
      'v-residencia': 'Uruguay',
      'v-calle': 'Av. 18 de Julio 1234',
      'v-ciudad': 'Montevideo',
      'v-provincia': 'Montevideo',
      'v-cp': '11100',
      'v-pasaporte': 'UY55443322',
      'v-ocupacion': 'Ingeniero Agrónomo',
      'j-motivo': 'turismo',
      'a-vinculo': 'pareja',
      'a-parentesco': 'novio',
      'a-vinculo-detalle': 'Somos novios desde 2023.',
      'a-tiempo-anios': '3',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos', 'transporte'],
      'transporte_mx': ['anfitrion'],
      companions: [
        { nombre: 'Martina Ortiz Blanco', genero: 'femenino', nacimiento: '1995-04-22', nacionalidad: 'Uruguaya', pasaporte: 'UY11002233', vinculo: 'familiar', parentesco: 'cunado', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '3', tiempo_meses: '0', ocupacion: 'Arquitecta', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Puerto Vallarta, Jalisco', actividades: 'Playa, malecón, avistamiento de ballenas.', aloj_nombre: 'Hotel Sheraton', aloj_calle: 'Paseo de la Marina 205', aloj_colonia: 'Marina Vallarta', aloj_delegacion: 'Puerto Vallarta', aloj_ciudad: 'Puerto Vallarta', aloj_estado: 'Jalisco', aloj_cp: '48354', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-17' },
        { ciudad: 'Sayulita, Nayarit', actividades: 'Surf, pueblo mágico, playa de los Muertos.', aloj_nombre: '', aloj_calle: 'Calle Marlin 15', aloj_colonia: 'Centro', aloj_delegacion: 'Bahía de Banderas', aloj_ciudad: 'Sayulita', aloj_estado: 'Nayarit', aloj_cp: '63734', fecha_desde: '2026-04-17', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C11-2dest-1comp-hijastro',
    desc: '2 destinos, 1 acompañante, familiar hijastro (no consanguíneo)',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Renato Emilio Vargas Ponce',
      'v-genero': 'masculino',
      'v-nacimiento': '2008-06-15',
      'v-nacionalidad': 'Hondureña',
      'v-residencia': 'Honduras',
      'v-calle': 'Col. Palmira, Calle Principal',
      'v-ciudad': 'Tegucigalpa',
      'v-provincia': 'Francisco Morazán',
      'v-cp': '11101',
      'v-pasaporte': 'HN33445566',
      'v-ocupacion': 'Estudiante de secundaria',
      'j-motivo': 'turismo',
      'a-vinculo': 'familiar',
      'a-parentesco': 'hijastro',
      'a-vinculo-detalle': '',
      'a-tiempo-anios': '6',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte', 'actividades'],
      'transporte_mx': ['anfitrion'],
      companions: [
        { nombre: 'Valeria Ponce de Vargas', genero: 'femenino', nacimiento: '1983-08-20', nacionalidad: 'Hondureña', pasaporte: 'HN77889900', vinculo: 'pareja', parentesco: 'conyuge', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '7', tiempo_meses: '0', ocupacion: 'Abogada', mismo_domicilio: 'no', residencia: 'Honduras', calle: 'Col. Palmira, Calle Principal 234', ciudad: 'Tegucigalpa', provincia: 'Francisco Morazán', cp: '11101' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Six Flags, Chapultepec, acuario Inbursa.', aloj_nombre: '', aloj_calle: 'Calle Reforma 456', aloj_colonia: 'Juárez', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06600', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-17' },
        { ciudad: 'Querétaro, Querétaro', actividades: 'Centro histórico, Peña de Bernal, viñedos.', aloj_nombre: 'Hotel Misión Grand', aloj_calle: 'Blvd. Bernardo Quintana 4050', aloj_colonia: 'Alamos', aloj_delegacion: 'Querétaro', aloj_ciudad: 'Querétaro', aloj_estado: 'Querétaro', aloj_cp: '76160', fecha_desde: '2026-04-17', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C12-2dest-1comp-gastosOtro',
    desc: '2 destinos, 1 acompañante, gastos con "otro" personalizado',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Alejandra Mora Castillo',
      'v-genero': 'femenino',
      'v-nacimiento': '1989-03-22',
      'v-nacionalidad': 'Panameña',
      'v-residencia': 'Panamá',
      'v-calle': 'Vía España 100',
      'v-ciudad': 'Ciudad de Panamá',
      'v-provincia': 'Panamá',
      'v-cp': '0801',
      'v-pasaporte': 'PA66778899',
      'v-ocupacion': 'Economista',
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Amigas del colegio.',
      'a-tiempo-anios': '18',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alimentos', 'otro'],
      'gastos-otro-texto': 'boletos de avión internos',
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      companions: [
        { nombre: 'Carlos Mora Castillo', genero: 'masculino', nacimiento: '1986-07-14', nacionalidad: 'Panameña', pasaporte: 'PA11223344', vinculo: 'familiar', parentesco: 'hermano', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '', tiempo_meses: '', ocupacion: 'Chef', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Guanajuato, Guanajuato', actividades: 'Callejoneada, Museo de las Momias, Alhóndiga.', aloj_nombre: 'Hotel Edelmira', aloj_calle: 'Calle Sopena 3', aloj_colonia: 'Centro', aloj_delegacion: 'Guanajuato', aloj_ciudad: 'Guanajuato', aloj_estado: 'Guanajuato', aloj_cp: '36000', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-17' },
        { ciudad: 'San Miguel de Allende, Guanajuato', actividades: 'Parroquia, galerías de arte, aguas termales.', aloj_nombre: '', aloj_calle: 'Calle Canal 14', aloj_colonia: 'Centro', aloj_delegacion: 'San Miguel de Allende', aloj_ciudad: 'San Miguel de Allende', aloj_estado: 'Guanajuato', aloj_cp: '37700', fecha_desde: '2026-04-17', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C13-1dest-0comp-actividades',
    desc: '1 destino, 0 acompañantes, actividades no remuneradas',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...flightExit,
      'v-nombre': 'Carolina Beatriz Silva Méndez',
      'v-genero': 'femenino',
      'v-nacimiento': '1996-10-12',
      'v-nacionalidad': 'Nicaragüense',
      'v-residencia': 'Nicaragua',
      'v-calle': 'Carretera a Masaya Km 4',
      'v-ciudad': 'Managua',
      'v-provincia': 'Managua',
      'v-cp': '14000',
      'v-pasaporte': 'NI99001122',
      'v-ocupacion': 'Trabajadora social',
      'j-motivo': 'actividades_no_remuneradas',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Compañeras de ONG.',
      'a-tiempo-anios': '4',
      'a-tiempo-meses': '6',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos'],
      'transporte_mx': ['transporte_publico'],
      companions: [],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Voluntariado en centro comunitario, talleres educativos.', aloj_nombre: '', aloj_calle: 'Calle Reforma 456', aloj_colonia: 'Juárez', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06600', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-24' },
      ],
    }),
  },
  {
    name: 'C14-2dest-1comp-maritimo-entry-exit',
    desc: '2 destinos, 1 acompañante, entrada/salida marítima',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...seaEntry, ...seaExit,
      'a-ciudad': 'Cancún',
      'a-estado': 'Quintana Roo',
      'a-calle': 'Blvd. Kukulcán Km 12',
      'a-colonia': 'Zona Hotelera',
      'a-delegacion': 'Benito Juárez',
      'a-cp': '77500',
      'v-nombre': 'Emily Sarah Johnson',
      'v-genero': 'femenino',
      'v-nacimiento': '1985-04-30',
      'v-nacionalidad': 'Canadiense',
      'v-residencia': 'Canadá',
      'v-calle': '789 Maple St',
      'v-ciudad': 'Toronto',
      'v-provincia': 'Ontario',
      'v-cp': 'M5H 2N2',
      'v-pasaporte': 'CA98765432',
      'v-ocupacion': 'Profesora universitaria',
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en un crucero en 2020.',
      'a-tiempo-anios': '6',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'no',
      'gastos_host_conceptos': [],
      'transporte_mx': ['auto_rentado', 'transporte_publico'],
      companions: [
        { nombre: 'Michael Thomas Johnson', genero: 'masculino', nacimiento: '1983-08-15', nacionalidad: 'Canadiense', pasaporte: 'CA12348765', vinculo: 'pareja', parentesco: 'conyuge', parentesco_otro: '', vinculo_detalle: '', tiempo_anios: '6', tiempo_meses: '0', ocupacion: 'Contador Público', mismo_domicilio: 'no', residencia: 'Canadá', calle: '45 Maple Drive, Unit 12', ciudad: 'Toronto', provincia: 'Ontario', cp: 'M5V 2T6' },
      ],
      destinos: [
        { ciudad: 'Cozumel, Quintana Roo', actividades: 'Buceo, snorkel, playas, recorrido en moto.', aloj_nombre: 'Hotel Cozumel Palace', aloj_calle: 'Av. Rafael Melgar Km 1.5', aloj_colonia: 'Centro', aloj_delegacion: 'Cozumel', aloj_ciudad: 'Cozumel', aloj_estado: 'Quintana Roo', aloj_cp: '77600', fecha_desde: '2026-05-01', fecha_hasta: '2026-05-05' },
        { ciudad: 'Cancún, Quintana Roo', actividades: 'Zona hotelera, Isla Mujeres, Museo Subacuático.', aloj_nombre: '', aloj_calle: 'Blvd. Kukulcán Km 14', aloj_colonia: 'Zona Hotelera', aloj_delegacion: 'Benito Juárez', aloj_ciudad: 'Cancún', aloj_estado: 'Quintana Roo', aloj_cp: '77500', fecha_desde: '2026-05-05', fecha_hasta: '2026-05-08' },
      ],
    }),
  },
  {
    name: 'C15-5dest-2comp-stress',
    desc: '5 destinos, 2 acompañantes — maximum stress test',
    data: cleanForCompleto({
      ...hostBase, ...visitorBase, ...flightEntry, ...{ ...flightExit, 'sal-fecha': '2026-05-10' },
      'j-motivo': 'turismo',
      'a-vinculo': 'amistad',
      'a-vinculo-detalle': 'Nos conocimos en un programa de intercambio cultural en 2015.',
      'a-tiempo-anios': '11',
      'a-tiempo-meses': '0',
      'gastos_anfitrion': 'si',
      'gastos_host_conceptos': ['alojamiento', 'alimentos', 'transporte', 'actividades', 'medicos'],
      'transporte_mx': ['auto_rentado', 'anfitrion', 'transporte_publico'],
      companions: [
        { nombre: 'Roberto Carlos Rodríguez Gómez', genero: 'masculino', nacimiento: '1988-05-22', nacionalidad: 'Venezolana', pasaporte: 'VZ55667700', vinculo: 'amistad', parentesco: '', parentesco_otro: '', vinculo_detalle: 'Amigo cercano desde hace años.', tiempo_anios: '10', tiempo_meses: '0', ocupacion: 'Ingeniero Civil', mismo_domicilio: 'no', residencia: 'Venezuela', calle: 'Calle Carabobo 78, Urb. El Paraíso', ciudad: 'Caracas', provincia: 'Distrito Capital', cp: '1020' },
        { nombre: 'Patricia Elena Domínguez Ávila', genero: 'femenino', nacimiento: '1992-12-01', nacionalidad: 'Venezolana', pasaporte: 'VZ88990011', vinculo: 'pareja', parentesco: 'novio', parentesco_otro: '', vinculo_detalle: 'Novia del acompañante.', tiempo_anios: '3', tiempo_meses: '6', ocupacion: 'Médica', mismo_domicilio: 'si' },
      ],
      destinos: [
        { ciudad: 'Ciudad de México, CDMX', actividades: 'Chapultepec, Zócalo, Coyoacán, Frida Kahlo.', aloj_nombre: 'Hotel St. Regis', aloj_calle: 'Paseo de la Reforma 439', aloj_colonia: 'Cuauhtémoc', aloj_delegacion: 'Cuauhtémoc', aloj_ciudad: 'Ciudad de México', aloj_estado: 'Ciudad de México', aloj_cp: '06500', fecha_desde: '2026-04-10', fecha_hasta: '2026-04-15' },
        { ciudad: 'Puebla, Puebla', actividades: 'Centro histórico, mole poblano, Cholula.', aloj_nombre: 'Hotel La Purificadora', aloj_calle: 'Callejón de la 10 Norte 802', aloj_colonia: 'Centro', aloj_delegacion: 'Puebla', aloj_ciudad: 'Puebla', aloj_estado: 'Puebla', aloj_cp: '72000', fecha_desde: '2026-04-15', fecha_hasta: '2026-04-18' },
        { ciudad: 'Oaxaca de Juárez, Oaxaca', actividades: 'Monte Albán, mezcal, Hierve el Agua, mercados.', aloj_nombre: '', aloj_calle: 'Calle García Vigil 411', aloj_colonia: 'Centro', aloj_delegacion: 'Oaxaca de Juárez', aloj_ciudad: 'Oaxaca de Juárez', aloj_estado: 'Oaxaca', aloj_cp: '68000', fecha_desde: '2026-04-18', fecha_hasta: '2026-04-22' },
        { ciudad: 'San Cristóbal de las Casas, Chiapas', actividades: 'Cañón del Sumidero, pueblo mágico, mercados.', aloj_nombre: 'Hotel Bo', aloj_calle: 'Av. 14 de Septiembre 2', aloj_colonia: 'Centro', aloj_delegacion: 'San Cristóbal de las Casas', aloj_ciudad: 'San Cristóbal de las Casas', aloj_estado: 'Chiapas', aloj_cp: '29200', fecha_desde: '2026-04-22', fecha_hasta: '2026-04-26' },
        { ciudad: 'Cancún, Quintana Roo', actividades: 'Playa, snorkel, Isla Mujeres, Chichén Itzá.', aloj_nombre: 'Hotel RIU Cancún', aloj_calle: 'Blvd. Kukulcán Km 5.5', aloj_colonia: 'Zona Hotelera', aloj_delegacion: 'Benito Juárez', aloj_ciudad: 'Cancún', aloj_estado: 'Quintana Roo', aloj_cp: '77500', fecha_desde: '2026-04-26', fecha_hasta: '2026-05-10' },
      ],
    }),
  },
];

// ════════════════════════════════════════════════════════════════════
// Generate all
// ════════════════════════════════════════════════════════════════════

async function main() {
  console.log(`Generating ${esenciales.length} Plan Esencial variants...`);
  for (const v of esenciales) {
    try {
      const buf = await generatePDF(v.data, 'esencial');
      const path = `${OUT_DIR}/${v.name}.pdf`;
      writeFileSync(path, buf);
      console.log(`  ✓ ${v.name} (${(buf.length / 1024).toFixed(1)} KB) — ${v.desc}`);
    } catch (err) {
      console.error(`  ✗ ${v.name} — ERROR: ${err.message}`);
    }
  }

  console.log(`\nGenerating ${completos.length} Plan Completo variants...`);
  for (const v of completos) {
    try {
      const buf = await generatePDF(v.data, 'completo');
      const path = `${OUT_DIR}/${v.name}.pdf`;
      writeFileSync(path, buf);
      console.log(`  ✓ ${v.name} (${(buf.length / 1024).toFixed(1)} KB) — ${v.desc}`);
    } catch (err) {
      console.error(`  ✗ ${v.name} — ERROR: ${err.message}`);
    }
  }

  console.log(`\nDone! Generated ${esenciales.length + completos.length} PDFs in ${OUT_DIR}/`);
}

main().catch(err => { console.error(err); process.exit(1); });
